server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    username: 'yassine'
    password: 'yassine'
    url: jdbc:postgresql://postgres:5432/notification
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    hibernate:
      ddl-auto: create-drop
    show-sql: true

  rabbitmq:
    template:
      exchange: internal.exchange
      default-receive-queue: notification.queue
      routing-key: internal.notification.routing-key
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


